// Code generated by tools/limbogen/gen.py from PrismarineJS minecraft-data (MIT). DO NOT EDIT.

package limbo

// packetIDs holds the packet IDs the limbo uses; -1 means absent in that version.
type packetIDs struct {
	Login              int32
	Position           int32
	SpawnPosition      int32
	KeepAlive          int32
	Chat               int32
	SystemChat         int32
	Abilities          int32
	GameEvent          int32
	CenterChunk        int32
	ChunkData          int32
	Commands           int32
	Disconnect         int32
	PluginMessage      int32
	InKeepAlive        int32
	InChat             int32
	InChatCommand      int32
	InTeleportConfirm  int32
	InPluginMessage    int32
	CfgRegistryData    int32
	CfgFeatureFlags    int32
	CfgFinish          int32
	CfgKeepAlive       int32
	CfgPluginMessage   int32
	CfgDisconnect      int32
	InCfgFinish        int32
	InCfgKeepAlive     int32
	InCfgPluginMessage int32
}

// packetTable is keyed by protocol version.
var packetTable = map[int32]packetIDs{
	5:   {Login: 1, Position: 8, SpawnPosition: 5, KeepAlive: 0, Chat: 2, SystemChat: -1, Abilities: 57, GameEvent: 43, CenterChunk: -1, ChunkData: 33, Commands: -1, Disconnect: 64, PluginMessage: 63, InKeepAlive: 0, InChat: 1, InChatCommand: -1, InTeleportConfirm: -1, InPluginMessage: 23, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},      // 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10 (pc/1.7)
	47:  {Login: 1, Position: 8, SpawnPosition: 5, KeepAlive: 0, Chat: 2, SystemChat: -1, Abilities: 57, GameEvent: 43, CenterChunk: -1, ChunkData: 33, Commands: -1, Disconnect: 64, PluginMessage: 63, InKeepAlive: 0, InChat: 1, InChatCommand: -1, InTeleportConfirm: -1, InPluginMessage: 23, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},      // 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9 (pc/1.8)
	107: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.9 (pc/1.9)
	108: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.9.1 (pc/1.9.2)
	109: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.9.2 (pc/1.9.2)
	110: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.9.3, 1.9.4 (pc/1.9.4)
	210: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.10, 1.10.1, 1.10.2 (pc/1.10)
	315: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.11 (pc/1.11)
	316: {Login: 35, Position: 46, SpawnPosition: 67, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.11.1, 1.11.2 (pc/1.11)
	335: {Login: 35, Position: 46, SpawnPosition: 69, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 43, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 12, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.12 (pc/1.12)
	338: {Login: 35, Position: 47, SpawnPosition: 70, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 44, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.12.1 (pc/1.12.1)
	340: {Login: 35, Position: 47, SpawnPosition: 70, KeepAlive: 31, Chat: 15, SystemChat: -1, Abilities: 44, GameEvent: 30, CenterChunk: -1, ChunkData: 32, Commands: -1, Disconnect: 26, PluginMessage: 24, InKeepAlive: 11, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 9, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.12.2 (pc/1.12.2)
	393: {Login: 37, Position: 50, SpawnPosition: 73, KeepAlive: 33, Chat: 14, SystemChat: -1, Abilities: 46, GameEvent: 32, CenterChunk: -1, ChunkData: 34, Commands: 17, Disconnect: 27, PluginMessage: 25, InKeepAlive: 14, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.13 (pc/1.13)
	401: {Login: 37, Position: 50, SpawnPosition: 73, KeepAlive: 33, Chat: 14, SystemChat: -1, Abilities: 46, GameEvent: 32, CenterChunk: -1, ChunkData: 34, Commands: 17, Disconnect: 27, PluginMessage: 25, InKeepAlive: 14, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.13.1 (pc/1.13.1)
	404: {Login: 37, Position: 50, SpawnPosition: 73, KeepAlive: 33, Chat: 14, SystemChat: -1, Abilities: 46, GameEvent: 32, CenterChunk: -1, ChunkData: 34, Commands: 17, Disconnect: 27, PluginMessage: 25, InKeepAlive: 14, InChat: 2, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.13.2 (pc/1.13.2)
	477: {Login: 37, Position: 53, SpawnPosition: 77, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.14 (pc/1.14)
	480: {Login: 37, Position: 53, SpawnPosition: 77, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.14.1 (pc/1.14.1)
	485: {Login: 37, Position: 53, SpawnPosition: 77, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.14.2 (pc/1.14.1)
	490: {Login: 37, Position: 53, SpawnPosition: 77, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.14.3 (pc/1.14.3)
	498: {Login: 37, Position: 53, SpawnPosition: 77, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.14.4 (pc/1.14.4)
	573: {Login: 38, Position: 54, SpawnPosition: 78, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 31, CenterChunk: 65, ChunkData: 34, Commands: 18, Disconnect: 27, PluginMessage: 25, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.15 (pc/1.15)
	575: {Login: 38, Position: 54, SpawnPosition: 78, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 31, CenterChunk: 65, ChunkData: 34, Commands: 18, Disconnect: 27, PluginMessage: 25, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.15.1 (pc/1.15.1)
	578: {Login: 38, Position: 54, SpawnPosition: 78, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 31, CenterChunk: 65, ChunkData: 34, Commands: 18, Disconnect: 27, PluginMessage: 25, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.15.2 (pc/1.15.2)
	735: {Login: 37, Position: 53, SpawnPosition: 66, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 16, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.16 (pc/1.16)
	736: {Login: 37, Position: 53, SpawnPosition: 66, KeepAlive: 32, Chat: 14, SystemChat: -1, Abilities: 49, GameEvent: 30, CenterChunk: 64, ChunkData: 33, Commands: 17, Disconnect: 26, PluginMessage: 24, InKeepAlive: 16, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.16.1 (pc/1.16.1)
	751: {Login: 36, Position: 52, SpawnPosition: 66, KeepAlive: 31, Chat: 14, SystemChat: -1, Abilities: 48, GameEvent: 29, CenterChunk: 64, ChunkData: 32, Commands: 16, Disconnect: 25, PluginMessage: 23, InKeepAlive: 16, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.16.2 (pc/1.16.2)
	753: {Login: 36, Position: 52, SpawnPosition: 66, KeepAlive: 31, Chat: 14, SystemChat: -1, Abilities: 48, GameEvent: 29, CenterChunk: 64, ChunkData: 32, Commands: 16, Disconnect: 25, PluginMessage: 23, InKeepAlive: 16, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.16.3 (pc/1.16.2)
	754: {Login: 36, Position: 52, SpawnPosition: 66, KeepAlive: 31, Chat: 14, SystemChat: -1, Abilities: 48, GameEvent: 29, CenterChunk: 64, ChunkData: 32, Commands: 16, Disconnect: 25, PluginMessage: 23, InKeepAlive: 16, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 11, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.16.4, 1.16.5 (pc/1.16.2)
	755: {Login: 38, Position: 56, SpawnPosition: 75, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 30, CenterChunk: 73, ChunkData: 34, Commands: 18, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.17 (pc/1.17)
	756: {Login: 38, Position: 56, SpawnPosition: 75, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 30, CenterChunk: 73, ChunkData: 34, Commands: 18, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.17.1 (pc/1.17.1)
	757: {Login: 38, Position: 56, SpawnPosition: 75, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 30, CenterChunk: 73, ChunkData: 34, Commands: 18, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.18, 1.18.1 (pc/1.18)
	758: {Login: 38, Position: 56, SpawnPosition: 75, KeepAlive: 33, Chat: 15, SystemChat: -1, Abilities: 50, GameEvent: 30, CenterChunk: 73, ChunkData: 34, Commands: 18, Disconnect: 26, PluginMessage: 24, InKeepAlive: 15, InChat: 3, InChatCommand: -1, InTeleportConfirm: 0, InPluginMessage: 10, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.18.2 (pc/1.18.2)
	759: {Login: 35, Position: 54, SpawnPosition: 74, KeepAlive: 30, Chat: -1, SystemChat: 95, Abilities: 47, GameEvent: 27, CenterChunk: 72, ChunkData: 31, Commands: 15, Disconnect: 23, PluginMessage: 21, InKeepAlive: 17, InChat: 4, InChatCommand: 3, InTeleportConfirm: 0, InPluginMessage: 12, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.19 (pc/1.19)
	760: {Login: 37, Position: 57, SpawnPosition: 77, KeepAlive: 32, Chat: -1, SystemChat: 98, Abilities: 49, GameEvent: 29, CenterChunk: 75, ChunkData: 33, Commands: 15, Disconnect: 25, PluginMessage: 22, InKeepAlive: 18, InChat: 5, InChatCommand: 4, InTeleportConfirm: 0, InPluginMessage: 13, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.19.1, 1.19.2 (pc/1.19.2)
	761: {Login: 36, Position: 56, SpawnPosition: 76, KeepAlive: 31, Chat: -1, SystemChat: 96, Abilities: 48, GameEvent: 28, CenterChunk: 74, ChunkData: 32, Commands: 14, Disconnect: 23, PluginMessage: 21, InKeepAlive: 17, InChat: 5, InChatCommand: 4, InTeleportConfirm: 0, InPluginMessage: 12, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1},  // 1.19.3 (pc/1.19.3)
	762: {Login: 40, Position: 60, SpawnPosition: 80, KeepAlive: 35, Chat: -1, SystemChat: 100, Abilities: 52, GameEvent: 31, CenterChunk: 78, ChunkData: 36, Commands: 16, Disconnect: 26, PluginMessage: 23, InKeepAlive: 18, InChat: 5, InChatCommand: 4, InTeleportConfirm: 0, InPluginMessage: 13, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.19.4 (pc/1.19.4)
	763: {Login: 40, Position: 60, SpawnPosition: 80, KeepAlive: 35, Chat: -1, SystemChat: 100, Abilities: 52, GameEvent: 31, CenterChunk: 78, ChunkData: 36, Commands: 16, Disconnect: 26, PluginMessage: 23, InKeepAlive: 18, InChat: 5, InChatCommand: 4, InTeleportConfirm: 0, InPluginMessage: 13, CfgRegistryData: -1, CfgFeatureFlags: -1, CfgFinish: -1, CfgKeepAlive: -1, CfgPluginMessage: -1, CfgDisconnect: -1, InCfgFinish: -1, InCfgKeepAlive: -1, InCfgPluginMessage: -1}, // 1.20, 1.20.1 (pc/1.20)
	764: {Login: 41, Position: 62, SpawnPosition: 82, KeepAlive: 36, Chat: -1, SystemChat: 103, Abilities: 54, GameEvent: 32, CenterChunk: 80, ChunkData: 37, Commands: 17, Disconnect: 27, PluginMessage: 24, InKeepAlive: 20, InChat: 5, InChatCommand: 4, InTeleportConfirm: 0, InPluginMessage: 15, CfgRegistryData: 5, CfgFeatureFlags: 7, CfgFinish: 2, CfgKeepAlive: 3, CfgPluginMessage: 0, CfgDisconnect: 1, InCfgFinish: 2, InCfgKeepAlive: 3, InCfgPluginMessage: 1},          // 1.20.2 (pc/1.20.2)
	765: {Login: 41, Position: 62, SpawnPosition: 84, KeepAlive: 36, Chat: -1, SystemChat: 105, Abilities: 54, GameEvent: 32, CenterChunk: 82, ChunkData: 37, Commands: 17, Disconnect: 27, PluginMessage: 24, InKeepAlive: 21, InChat: 5, InChatCommand: 4, InTeleportConfirm: 0, InPluginMessage: 16, CfgRegistryData: 5, CfgFeatureFlags: 8, CfgFinish: 2, CfgKeepAlive: 3, CfgPluginMessage: 0, CfgDisconnect: 1, InCfgFinish: 2, InCfgKeepAlive: 3, InCfgPluginMessage: 1},          // 1.20.3, 1.20.4 (pc/1.20.3)
}

// codecFiles maps protocol versions to embedded registry codec files.
var codecFiles = map[int32]string{
	735: "data/codec_1.16.nbt.gz",
	736: "data/codec_1.16.nbt.gz",
	751: "data/codec_1.16.2.nbt.gz",
	753: "data/codec_1.16.2.nbt.gz",
	754: "data/codec_1.16.2.nbt.gz",
	755: "data/codec_1.17.nbt.gz",
	756: "data/codec_1.17.nbt.gz",
	757: "data/codec_1.18.nbt.gz",
	758: "data/codec_1.18.2.nbt.gz",
	759: "data/codec_1.19.nbt.gz",
	760: "data/codec_1.19.2.nbt.gz",
	761: "data/codec_1.19.2.nbt.gz",
	762: "data/codec_1.19.4.nbt.gz",
	763: "data/codec_1.20.nbt.gz",
	764: "data/codec_1.20.2.nbt.gz",
	765: "data/codec_1.20.2.nbt.gz",
}

// dimensionFiles maps protocol versions to embedded dimension-type elements (1.16.2-1.18.2 Join Game).
var dimensionFiles = map[int32]string{
	751: "data/dim_1.16.2.nbt.gz",
	753: "data/dim_1.16.2.nbt.gz",
	754: "data/dim_1.16.2.nbt.gz",
	755: "data/dim_1.17.nbt.gz",
	756: "data/dim_1.17.nbt.gz",
	757: "data/dim_1.18.nbt.gz",
	758: "data/dim_1.18.2.nbt.gz",
}
